# Generated by Django 2.2 on 2019-04-15 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carpoolhost', '0002_auto_20190415_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmember',
            name='datetime_of_reg',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regmember',
            name='datetime_of_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='regmember',
            name='memberemail',
            field=models.EmailField(help_text='비밀번호 찾기용 이메일', max_length=254),
        ),
    ]
