# Generated by Django 2.2 on 2019-04-15 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpoolhost', '0003_auto_20190415_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hostnumber', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_host', models.DateField(default=datetime.datetime(2019, 4, 15, 17, 33, 43, 608466))),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpoolhost.Member')),
            ],
        ),
    ]
