# Generated by Django 2.2 on 2019-04-15 09:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carpoolhost', '0005_auto_20190415_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='car_num',
            field=models.CharField(blank=True, help_text='차량번호', max_length=10),
        ),
        migrations.AddField(
            model_name='host',
            name='datetime_of_reg',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='datetime_of_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ending_tf',
            field=models.BooleanField(default=False, help_text='Host 종료여부'),
        ),
        migrations.AddField(
            model_name='host',
            name='how_many_guest',
            field=models.PositiveSmallIntegerField(default=3, help_text='탑승인원', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='host',
            name='where_to_go',
            field=models.CharField(blank=True, help_text='목적지', max_length=40),
        ),
        migrations.AlterField(
            model_name='host',
            name='date_of_host',
            field=models.DateField(default=django.utils.timezone.now, help_text='탑승일자'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hour_of_host',
            field=models.CharField(choices=[('17', '오후 5시'), ('18', '오후 6시'), ('19', '오후 7시'), ('20', '오후 8시'), ('21', '오후 9시'), ('22', '오후 10시'), ('23', '오후 11시'), ('24', '자정'), ('01', '새벽 1시')], default='06', help_text='탑승 시각', max_length=2),
        ),
        migrations.AlterField(
            model_name='host',
            name='minutes_of_host',
            field=models.CharField(choices=[('00', '정각'), ('15', '15분'), ('30', '30분'), ('45', '45분')], default='00', help_text='탑승 분', max_length=2),
        ),
    ]
