# Generated by Django 2.2 on 2019-04-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpoolhost', '0006_auto_20190415_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientnumber', models.AutoField(help_text='탑승신청 고유번호', primary_key=True, serialize=False)),
                ('datetime_of_reg', models.DateTimeField(auto_now_add=True)),
                ('datetime_of_update', models.DateTimeField(auto_now=True)),
                ('clientmembernumber', models.ForeignKey(help_text='탑승자 사번', null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpoolhost.Member')),
                ('hostnumber', models.ForeignKey(help_text='호스트 고유번호', null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpoolhost.Host')),
            ],
        ),
    ]
